### ISSUE TITLE
SCT installation instructions for macOS

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-sct-user-guide#1]
Hello,
At: https://docs.aws.amazon.com/SchemaConversionTool/latest/userguide/CHAP_Installing.html there's a minor mistake for macOS instructions:
"Drag AWS Schema Conversion Tool-1.0.build-number.dmg to the Applications folder. "
it should read
"Drag AWS Schema Conversion Tool to the Applications folder."

**Comment by amazoncathan** [comment]
Fixed in next update. Thank you!
