### ISSUE TITLE
SCT Support from Oracle to SQL Server

### ISSUE THREAD

**Issue by ashuvillage** [awsdocs/aws-sct-user-guide#4]
Hi Team,
I have a use case for migrating oracle to SQL server but as of now, I don't see an option/support in the Scheme conversion tool. But in DMS I can see in source and target there is a possibility to migrate oracle to SQL server. 
Can we still migrate without that or can you enable this feature in SCT

**Comment by surajtikoo** [comment]
Hi Team,
I have a use case for migrating oracle to SQL server but as of now, I don't see an option/support in the Scheme conversion tool. But in DMS I can see in source and target there is a possibility to migrate oracle to SQL server.
Can we still migrate without that or can you enable this feature in SCT

**Comment by chrmcguire** [comment]
You can use AWS Database Migration Service (DMS) to migrate data to any of the targets supported by AWS DMS, including SQL Server. However, the AWS Schema Conversion Tool (SCT) User Guide does not list SQL Server as a target that you can convert your existing Oracle database schema to using SCT.   Will pass your comment on to product management.
